name: Docker CVE by anchore with vulnerablities
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the container image
        run: docker build --tag localbuild/vulnerableimage1:latest vulnerableImages
      - uses: anchore/scan-action@v3
        with:
          image: "localbuild/vulnerableimage1:latest"
          fail-build: true
          severity-cutoff: low
          output-format: table
